config/routes.rb
# rubocop:disable Metrics/LineLength
Rails.application.routes.draw do
  resources :friendships, path: 'close_friends' do
    member do
      post :accept
    end
  end

  resources :comments
  resources :conversations do
    member do
      post :add_participant
    end
  end

  resources :participations do
    member do
      post :mark_as_unread
      post :mark_as_read
      post :unmute
      post :mute
    end
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { registrations: 'registrations' }
  devise_scope :user do
    post 'toggle_friendship_notification', action: 'toggle_friendship_notification', controller: 'registrations'
    post 'toggle_conversation_notification', action: 'toggle_conversation_notification', controller: 'registrations'
    post 'toggle_reply_notification', action: 'toggle_reply_notification', controller: 'registrations'
  end

  get 'notification_settings' => 'pages#notification_settings'
  root 'pages#home'
end

app/models/conversation.rb
# conversation model
class Conversation < ActiveRecord::Base
  validates_presence_of :user_id, :subject

  extend FriendlyId
  friendly_id :subject, use: :slugged

  def should_generate_new_friendly_id?
    subject_changed?
  end

  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  belongs_to :friendship

  has_many :participations, -> { order 'id ASC' }, dependent: :destroy
  has_many :participants, through: :participations, source: :user
  has_many :engaged_participations, through: :comments, source: :participation

  has_many :comments, -> { order 'id ASC' }

  def my_participation(current_user_id)
    Participation.find_by(user_id: current_user_id, conversation_id: id)
  end

  def ordered_participants
    names = []
    participations.each do |p|
      names << p.user.first_name
    end
    names
  end
end

app/controllers/conversations_controller.rb
# rubocop:disable Metrics/LineLength
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy, :add_participant]
  before_action :authenticate_user!
  before_action :authenticate_admin, only: [:index]
  before_action :authenticate_owner, only: [:edit, :update, :destroy]
  before_action :authenticate_participation, only: [:show]

  def index
    @conversations = Conversation.all
  end

  def show
    @participation = @conversation.my_participation(current_user.id)
    @comment = @participation.comments.build
    @comments = @conversation.comments
  end

  def new
    @conversation = current_user.conversations.build
  end

  def edit
  end

  def create
    @conversation = current_user.conversations.build(conversation_params)
    @conversation.recipient_ids = params[:recipient].nil? ? [] : params[:recipient][:ids]

    respond_to do |format|
      if params[:comment][:content].present? && !params[:recipient].nil? && @conversation.save
        owner_participation = @conversation.participations.build(user_id: current_user.id, read: true, others_count: @conversation.recipient_ids.length)
        owner_participation.save
        @conversation.recipient_ids.each do |id|
          friend_participation = @conversation.participations.build(user_id: id, others_count: @conversation.recipient_ids.length)
          friend_participation.save
          UserNotifier.new_conversation_email(@conversation, current_user, id).deliver if friend_participation.user.conversation_notifications?
        end
        comment = @conversation.comments.build(participation_id: owner_participation.id, content: params[:comment][:content])
        comment.save
        format.html { redirect_to @conversation, notice: 'Conversation started.' }
      else
        format.html { render action: 'new' }
        unless params[:comment][:content].present?
          @conversation.errors.add(:subject, '& first comment cannot be blank.')
        end
        if params[:recipient].nil?
          @conversation.errors.add(:recipient, 'cannot be blank.')
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Conversation deleted.' }
    end
  end

  def add_participant
    # raise params
    @conversation.recipient_ids_will_change!
    @conversation.update_attribute(:recipient_ids, @conversation.recipient_ids << params[:friend_id])
    @conversation.save

    friend_participation = @conversation.participations.build(user_id: params[:friend_id], others_count: @conversation.recipient_ids.length)
    friend_participation.save
    UserNotifier.new_participant_email(@conversation, current_user, params[:friend_id]).deliver if friend_participation.user.conversation_notifications?

    @conversation.participations.each do |part|
      part.update_attribute(:others_count, @conversation.recipient_ids.length)
    end

    redirect_to @conversation, notice: 'Friend added.'
  end

  private

  def set_conversation
    @conversation = Conversation.friendly.find(params[:id])
  end

  def authenticate_owner
    unless @conversation.owner == current_user
      redirect_to root_path, notice: "You don't have persmission to view this page."
    end
  end

  def authenticate_participation
    unless @conversation.participants.any? { |p| p == current_user }
      redirect_to root_path, notice: "You don't have persmission to view this page."
    end
  end

  def conversation_params
    params.require(:conversation).permit(:subject, :recipient_ids, :source_link, :slug, :user_id)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_for(@conversation) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation center">
      <% @conversation.errors.full_messages.each do |message| %>
        <%= content_tag(:div, message, class: 'alert alert-danger center') %>
      <% end %>
    </div>
  <% end %>

  <div class="section">

    <div class="top-bar">
      <div class="main-nav-text"><a href="<%= root_path %>">Start Conversation</a></div>
    </div>

    <div class="fit-conversation">
      <div class="fit-form-to">
        <div class="form-label-to">To:</div>
        <div class="fit-recipients" data-toggle="buttons">
            <% current_user.all_active_friendships.each do |friendship| %>
              <% friend = friendship.get_friend(current_user) %>
              <label class="btn btn-checkbox">
                <%= check_box("recipient", "ids", {:multiple => true}, friend.id, nil) %>
                <%= friend.first_name %>
              </label>
          <% end %>
        </div>
      </div>
      
      <div class="fit-form">
        <%= f.text_field :subject, placeholder: "question or topic of discussion", class: "form-format form-format-subject", autofocus: true %>
        <span class="form-label">Subject:</span>
      </div>
      
      <div class="fit-form">
        <%= f.text_field :source_link, placeholder: "http://...  enter URL of article or video (optional)", class: "form-format form-format-link" %>
        <span class="form-label">Inspiration:</span>
      </div>
    </div>

    <% unless params[:action] == 'edit' %>
      <%= fields_for (Comment.new) do |fc| %>
        <div class="page-content fit-top-border">
          <h5>What are your thoughts?</h5>
          <%= fc.trix_editor :content, placeholder: 'what are your thoughts?' %>
        </div>
      <% end %>
    <% end %>

    <div class="bottom-bar center fit-top-border">
      <%= f.submit 'SEND', class: "btn btn-primary btn-primary-action" %>
      <%= link_to 'DISCARD', root_path, class: "btn btn-default btn-default-action" %>
    </div>
  </div>

<% end %>

app/views/conversations/edit.html.erb
<%= render 'form' %>

app/views/conversations/index.html.erb
<h1>Listing conversations</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Source author</th>
      <th>Source link</th>
      <th>Source content</th>
      <th>Slug</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.subject %></td>
        <td><%= conversation.recipient_ids %></td>
        <td><%= conversation.source_link %></td>
        <td><%= conversation.slug %></td>
        <td><%= conversation.user_id %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<%= render 'form' %>

app/views/conversations/show.html.erb
<div class="section">

  <div class="top-bar">
    
    <div class="pull-right">
      <%= link_to '<i class="fa fa-envelope-o"></i>'.html_safe, mark_as_unread_participation_path(@participation), method: :post, class: "btn btn-primary btn-read-icon" %>

      <a href="#" class="dropdown-toggle btn btn-more-icon" data-toggle="dropdown">
          <i class="fa fa-angle-down"></i>
      </a>
      <ul class="dropdown-menu right-dropdown">
        <% if @conversation.participants.count > 1 %>
          <% if @participation.unmute? %>
            <li><%= link_to "Mute Discussion", mute_participation_path(@participation), method: :post %></li>      
          <% else %>
            <li><%= link_to "Umute Discussion", unmute_participation_path(@participation), method: :post %></li>
          <% end %>
        <% end %>

        <% if @conversation.owner == current_user %>
          <li><%= link_to "Delete", @conversation, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete-link" %></li>
        <% end %>
      </ul>
    </div>

    <div class="main-nav-text">
      <a href="<%= root_path %>">
        <div class="hidden-xs">
          <i class="fa fa-fw fa-lg fa-chevron-left"></i> Conversations
          <%= "(#{current_user.participations.unread.count})" if current_user.participations.unread.count > 0 %>
        </div>
        <div class="visible-xs">
          <i class="fa fa-lg fa-chevron-left"></i>
        </div>
      </a>
    </div>
  </div>

  <div class="page-content">

    <span class="time-stamp"><%= @conversation.created_at.strftime('%b %d, %Y') %></span>
    <div class="subtitle text-truncate-75">
      <%= @conversation.ordered_participants.join(', ') %>
      <%= "(" + @comments.count.to_s + ")" if @comments.count > 1 %>
    </div>

    <h1><%= @conversation.subject %></h1>
    
    <div class="subtitle">
      <% unless @conversation.source_link.empty? %>
        <% if ( @conversation.source_link =~ /^http/ ) %>
          <%= link_to "Inspiration", @conversation.source_link %>
        <% else %>
          <%= link_to "Inspiration", "http://#{@conversation.source_link}" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <% @comments.tap do |*older_comments, last_comment| %>

    <% older_comments.each do |c| %>

      <div class="fit-comment toggleable" id="comment-<%= c.id %>" onclick="show('comment-<%= c.id %>-full', 'comment-<%= c.id %>')"
        style="display:<%= c.created_at - @participation.updated_at > -120 ? 'none' : 'block' %>;">
        <span class="time-stamp hidden-xs"><%= time_ago(c.created_at) %></span>
        <span class="time-stamp visible-xs"><%= time_ago_short(c.created_at) %></span>
        <div class="text-truncate-preview">
          <h5 class="pull-left"><%= c.commenter.first_name %></h5>
          <span class="toggleable-preview-text"><%= strip_tags(c.content.gsub('<br>',' ').gsub('&nbsp;',' ')) %></span>
        </div>
      </div>

      <div id="comment-<%= c.id %>-full" onclick="show('comment-<%= c.id %>', 'comment-<%= c.id %>-full')"
        style="display:<%= c.created_at - @participation.updated_at > -120 ? 'block' : 'none' %>;"">
        <div class="fit-comment toggleable">
          <span class="time-stamp hidden-xs"><%= time_ago(c.created_at) %></span>
          <span class="time-stamp visible-xs"><%= time_ago_short(c.created_at) %></span>
          <h5><%= c.commenter.first_name %></h5>
        </div>

        <div class="fit-comment-content">
          <p><%= c.content.gsub('div>', 'p>').html_safe %></p>
        </div>
      </div>

    <% end %>

    <div class="fit-comment">
      <span class="time-stamp hidden-xs"><%= time_ago(last_comment.created_at) %></span>
      <span class="time-stamp visible-xs"><%= time_ago_short(last_comment.created_at) %></span>
      <h5><%= last_comment.commenter.first_name %></h5>
    </div>

    <div class="fit-comment-content fit-last-comment">
      <p><%= last_comment.content.gsub('div>', 'p>').html_safe %></p>
    </div>

  <% end %>

</div>

<div class="section-wayt">
  <%= form_for (@comment) do |f| %>
    <%= f.hidden_field :participation_id, value: @participation.id %>
    <%= f.hidden_field :conversation_id, value: @conversation.id %>

    <div class="fit-wayt-to fit-bottom-border preview-text">

      <div class="pull-left">
        <a href="#" class="dropdown-toggle btn btn-wayt-to" data-toggle="dropdown">+</a>
        <ul class="dropdown-menu wayt-to-dropdown">
          <% current_user.all_active_friendships.each do |friendship| %>
            <% friend = friendship.get_friend(current_user) %>
            <% if @conversation.ordered_participants.any? { |f| f == friend.first_name } %>
              <li class="disabled"><%= link_to friend.first_name, "#", method: :post %></li>
            <% else %>
              <li><%= link_to friend.first_name, add_participant_conversation_path(friend_id: friend.id), method: :post %></li>
            <% end %>   
          <% end %>
        </ul>
      </div>

      <div class="preview-text">
        <span class="hidden-xs">To: &nbsp; </span> 
        <% if @conversation.participants.count > 1 %>
          <%= @conversation.ordered_participants.select { |p| p != current_user.first_name }.join(', ') %>
        <% else %>
          Self
        <% end %>
      </div>

    </div>

    <div class="page-content">  
      <h5><%= current_user.first_name %></h5>
      
      <%= f.trix_editor :content, placeholder: 'what are your thoughts?' %>
    </div>
    <div class="bottom-bar center fit-top-border">
      <%= f.submit 'SEND', class: "btn btn-primary btn-primary-action" %>
      <%= link_to 'DISCARD', conversation_path(@conversation), class: "btn btn-default btn-default-action" %>
    </div>
  <% end %>
</div>


<script type="text/javascript">
  function show(target, source){
     document.getElementById(target).style.display = 'block';
     document.getElementById(source).style.display = 'none';
  }
</script>