config/routes.rb
# rubocop:disable Metrics/LineLength
Rails.application.routes.draw do
  resources :friendships, path: 'close_friends' do
    member do
      post :accept
    end
  end

  resources :comments
  resources :conversations do
    member do
      post :add_participant
    end
  end

  resources :participations do
    member do
      post :mark_as_unread
      post :mark_as_read
      post :unmute
      post :mute
    end
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { registrations: 'registrations' }
  devise_scope :user do
    post 'toggle_friendship_notification', action: 'toggle_friendship_notification', controller: 'registrations'
    post 'toggle_conversation_notification', action: 'toggle_conversation_notification', controller: 'registrations'
    post 'toggle_reply_notification', action: 'toggle_reply_notification', controller: 'registrations'
  end

  get 'notification_settings' => 'pages#notification_settings'
  root 'pages#home'
end

app/views/user_notifier/accept_friend_request_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Hi <%= @user.first_name %>,</p>
	<p>
		<%= @friend.first_name %> has accepted your friend request.
		<br>Enjoy having in-depth conversations, discussions and debates.
	</p>
	<p>
		<a href="<%= new_conversation_url %>">Start a new conversation.</a>
	</p>
	<p>
		Best,
		<br>Pranav Gupta
		<br><a href="root_url">what are your thoughts?</a>
	</p>
</body>
</html>

app/views/user_notifier/admin_new_user_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p><%= @user.name %> just signed up!</p>
</body>
</html>

app/views/user_notifier/friend_request_accept_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Hi <%= @user.first_name %>,</p>
	<p>
		<%= @friend.first_name %> has accepted your friend request.
		<br>Enjoy having in-depth conversations, discussions and debates.
	</p>
	<p>
		<a href="<%= new_conversation_url %>">Start a conversation.</a> or simply add to them to ongoing ones.
	</p>
	<p>
		Best,
		<br>Pranav
		<br><a href="root_url">what are your thoughts?</a>
	</p>
</body>
</html>

app/views/user_notifier/friend_request_send_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Hi <%= @friend.first_name %>,</p>
	<p>
		<%= @user.first_name %> enjoys the in-depth conversations and discussions you both have.
		<br>They'd like to continue doing so even when its harder to meet in person. 
	</p>
	<p>
		<%= @user.first_name %> has sent you a <a href="<%= friendships_url %>">friend request</a>.
		<br>Accept it to get started!
	</p>
	<p>
		Best,
		<br>Pranav
		<br><a href="root_url">what are your thoughts?</a>
	</p>
</body>
</html>

app/views/user_notifier/new_comment_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Hi <%= @friend.first_name %>,</p>
	<p>
		<%= @user.first_name %> wrote a reply to your mutual discussion.
		<br>They would love to get your inputs.
	</p>
	<p>
		Read and reply here: <a href="<%= conversation_url(@conversation) %>"><%= @conversation.subject %></a>.
	</p>
	<p>
		Best,
		<br>Pranav
		<br><a href="root_url">what are your thoughts?</a>
	</p>
</body>
</html>

app/views/user_notifier/new_conversation_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Hi <%= @friend.first_name %>,</p>
	<p>
		<%= @user.first_name %> started a new discussion - <%= @conversation.subject %> and would love to get your inputs.
	</p>
	<p>
		Read the discussion <a href="<%= conversation_url(@conversation) %>">here</a>.
	</p>
	<p>
		Best,
		<br>Pranav Gupta
		<br><a href="root_url">what are your thoughts?</a>
	</p>
</body>
</html>

app/views/user_notifier/new_participant_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Hi <%= @friend.first_name %>,</p>
	<p>
		<%= @user.first_name %> invited you to contribute to their discussion - <%= @conversation.subject %>
		<br>They would love to get your inputs.
	</p>
	<p>
		Read the discussion <a href="<%= conversation_url(@conversation) %>">here</a>.
	</p>
	<p>
		Best,
		<br>Pranav
		<br><a href="root_url">what are your thoughts?</a>
	</p>
</body>
</html>

app/views/user_notifier/send_friend_request_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Hi <%= @friend.first_name %>,</p>
	<p>
		<%= @user.first_name %> enjoys the in-depth conversations and discussions you both have.
		<br>They'd like to continue doing so even when its harder to meet in person. 
	</p>
	<p>
		<%= @user.first_name %> has sent you a <a href="<%= friendships_url %>">friend request</a>.
		<br>Accept it to get started!
	</p>
	<p>
		Best,
		<br>Pranav Gupta
		<br><a href="root_url">what are your thoughts?</a>
	</p>
</body>
</html>

app/views/user_notifier/welcome_email.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
	<p>Thanks for signing up for 'what are your thoughts?', <%= @user.first_name %>!</p>
	<p>
		The first thing you'll need to do is <a href="new_friendship_url">add a couple of friends</a> using their email ids.
		<br>Then you can compose conversations and send it to them, just as you'd do in gmail. 
	</p>
	<p>
		Have fun debating, discussing and reflecting on ideas with your close friends. 
		<br>Welcome :)
	</p>
	<p>
		Best,
		<br>Pranav
		<br><a href="root_url">what are your thoughts?</a>
	</p>
</body>
</html>