config/routes.rb
# rubocop:disable Metrics/LineLength
Rails.application.routes.draw do
  resources :friendships, path: 'close_friends' do
    member do
      post :accept
    end
  end

  resources :comments
  resources :conversations do
    member do
      post :add_participant
    end
  end

  resources :participations do
    member do
      post :mark_as_unread
      post :mark_as_read
      post :unmute
      post :mute
    end
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { registrations: 'registrations' }
  devise_scope :user do
    post 'toggle_friendship_notification', action: 'toggle_friendship_notification', controller: 'registrations'
    post 'toggle_conversation_notification', action: 'toggle_conversation_notification', controller: 'registrations'
    post 'toggle_reply_notification', action: 'toggle_reply_notification', controller: 'registrations'
  end

  get 'notification_settings' => 'pages#notification_settings'
  root 'pages#home'
end

app/models/friendship.rb
# friendship model
class Friendship < ActiveRecord::Base
  validates_presence_of :user_id, :friend_id, :status

  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: :friend_id

  def pending
    status == 'pending' ? true : false
  end

  def get_friend(current_user)
    friend.id == current_user.id ? user : friend
  end
end

app/controllers/friendships_controller.rb
# rubocop:disable Metrics/LineLength
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy, :accept]
  before_action :authenticate_involvement, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_admin, only: [:index]
  before_action :authenticate_user!

  def index
    @friendships = current_user.all_friendships
    @pending_count = @friendships.select { |f| f.status == 'pending' }.count
  end

  def show
  end

  def new
    @friendship = current_user.friendships.build
  end

  def edit
  end

  def create
    if params[:friend_email] == ''
      # empty
      respond_to do |format|
        format.html { redirect_to new_friendship_path, notice: 'Friend\'s email is required.' }
      end
    else

      friend = User.find_by(email: params[:friend_email])
      if friend.nil?
        # non-user
        respond_to do |format|
          format.html { redirect_to new_friendship_path, notice: "Friend not found!<br>The email <b>#{params[:friend_email]}</b> you tried might be incorrect <br>Or friend may not be an existing WAYT member.".html_safe }
        end

      elsif friend == current_user
        # current user
        respond_to do |format|
          format.html { redirect_to new_friendship_path, notice: 'I see what you did there! :)'.html_safe }
        end

      elsif current_user.friendships.any? { |p| p.friend_id == friend.id } || current_user.inverse_friendships.any? { |p| p.user_id == friend.id }
        # existing friend
        respond_to do |format|
          format.html { redirect_to new_friendship_path, notice: "<b>#{friend.first_name}</b> is already a friend!".html_safe }
        end

      elsif friend.friendships.count + friend.inverse_friendships.count == 5 # TODO: update
        # friend has full network
        respond_to do |format|
          format.html { redirect_to new_friendship_path, notice: "<b>#{friend.first_name}</b> already has maximum number of allowable friends!<br>Please ask them to make space before trying again".html_safe }
        end

      else
        # create new friendship
        @friendship = current_user.friendships.build(friend_id: friend.id)

        respond_to do |format|
          if @friendship.save
            UserNotifier.friend_request_send_email(@friendship.user, @friendship.friend).deliver if @friendship.friend.friendship_notifications?
            format.html { redirect_to friendships_path, notice: 'Friend request sent.' }
          else
            format.html { render action: 'new' }
          end
        end
      end

    end
  end

  def update
    # raise params
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Updated friendship.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url, notice: 'Friend lost.' }
    end
  end

  def accept
    @friendship.update_attribute(:status, 'active')
    UserNotifier.friend_request_accept_email(@friendship.user, @friendship.friend).deliver if @friendship.user.friendship_notifications?
    redirect_to friendships_path, notice: 'Friend request accepted. You can now have discussions with them.'
  end

  private

  def set_friendship
    @friendship = Friendship.find(params[:id])
  end

  def authenticate_involvement
    unless @friendship.user == current_user || @friendship.friend == current_user
      redirect_to root_path, notice: "You don't have persmission to view this page."
    end
  end

  def friendship_params
    params.require(:friendship).permit(:user_id, :friend_id, :status)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation center">
      <% @friendship.errors.full_messages.each do |message| %>
        <%= content_tag(:div, message, class: 'alert alert-danger center') %>
      <% end %>
    </div>
  <% end %>

  <div class="section">

    <div class="top-bar">
      <div class="main-nav-text"><a href="<%= friendships_path %>">Find & Add Friend</a></div>
    </div>

    <div class="fit-conversation">
      <div class="fit-form-to">
        <%= email_field_tag :friend_email, value = nil, placeholder: "email id", class: "form-format form-format-email", :autofocus => true %>
        <div class="form-label">Enter Friend's Email:</div>
      </div>
    </div>
    
    <%= f.hidden_field :status %>
    <%= f.hidden_field :user_id %>

    <div class="bottom-bar center fit-top-border">
      <%= f.submit 'SEND REQUEST', class: "btn btn-primary btn-primary-action" %>
      <%= link_to 'CANCEL', friendships_path, class: "btn btn-default btn-default-action" %>
    </div>
  </div>

<% end %>

app/views/friendships/edit.html.erb
<%= render 'form' %>

app/views/friendships/index.html.erb
<div class="section">

  <div class="top-bar">
    <%= link_to "ADD FRIEND", new_friendship_path, class: "pull-right btn btn-primary btn-primary-action" %>
    <div class="main-nav-text">
      <a href="<%= friendships_path %>">
        Close Friends <%= "(#{@pending_count})" if @pending_count > 0 %>
      </a>
    </div>
  </div>

  <div class="fit-list">
    <% @friendships.each do |friendship| %>
      <div class="fit-list-item">

        <% if friendship.pending %>
          <% if friendship.friend == current_user %>
            <h5 class="text-truncate-75"><%= friendship.user.name %></h5>
            <div class="recipient-text text-truncate-75">Pending Request</div>
            <%= link_to 'ACCEPT', accept_friendship_path(friendship), method: :post, class: 'btn btn-primary btn-primary-action btn-in-list' %>
          <% else  %>
            <h5 class="text-truncate-75"><%= friendship.friend.name %></h5>
            <div class="recipient-text text-truncate-75">Request Sent <em>(awaiting response)</em></div>
            <%= link_to 'DELETE', friendship, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-default-action btn-in-list' %>
          <% end %>
        <% else  %>
          <h5 class="text-truncate-75">
            <%= friendship.get_friend(current_user).name %>
          </h5>
          <div class="recipient-text text-truncate-75">Since <%= friendship.created_at.strftime('%b, %Y') %></div>
          <%= link_to 'UNFRIEND', friendship, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-default-action btn-in-list' %>
        <% end %>

      </div>    
    <% end %>
  </div>

</div>

app/views/friendships/new.html.erb
<%= render 'form' %>

app/views/friendships/show.html.erb
<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @friendship.status %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>