config/routes.rb
# rubocop:disable Metrics/LineLength
Rails.application.routes.draw do
  resources :friendships, path: 'close_friends' do
    member do
      post :accept
    end
  end

  resources :comments
  resources :conversations do
    member do
      post :add_participant
    end
  end

  resources :participations do
    member do
      post :mark_as_unread
      post :mark_as_read
      post :unmute
      post :mute
    end
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { registrations: 'registrations' }
  devise_scope :user do
    post 'toggle_friendship_notification', action: 'toggle_friendship_notification', controller: 'registrations'
    post 'toggle_conversation_notification', action: 'toggle_conversation_notification', controller: 'registrations'
    post 'toggle_reply_notification', action: 'toggle_reply_notification', controller: 'registrations'
  end

  get 'notification_settings' => 'pages#notification_settings'
  root 'pages#home'
end

app/views/pages/_conversation_list.html.erb
<div class="top-bar">
	<%= link_to "COMPOSE", new_conversation_path, class: "pull-right btn btn-primary btn-primary-action" %>
	<div class="main-nav-text">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			Conversations <%= "(#{@participations.unread.count})" if @participations.unread.count > 0 %>
		</a>
		<ul class="dropdown-menu left-dropdown">
			<li><%= link_to "Conversations", root_path, class: "active-link" %></li>
			<li><%= link_to "Close Friends", friendships_path %></li>
		</ul>
	</div>
</div>


<div class="fit-list">
	<% @participations.each do |part| %>
		<div class="fit-list-actions">
			<% if part.unread? %>
				<%= link_to '<i class="fa fa-fw fa-square"></i>'.html_safe, mark_as_read_participation_path(part), method: :post, class: "action-unread" %>
			<% else %>
				<%= link_to '<i class="fa fa-fw fa-square-o"></i>'.html_safe, mark_as_unread_participation_path(part), method: :post, class: "action-read" %>
			<% end %>
		</div>

		<a href="<%= participation_path(part) %>">
			<% c = part.conversation %>
			<div class="fit-list-item">
				<span class="time-stamp hidden-xs"><%= time_ago(c.comments.last.created_at) %></span>
				<span class="time-stamp visible-xs"><%= time_ago_short(c.comments.last.created_at) %></span>

				<h5 class="text-truncate-75"><%= c.subject %></h5>
				
				<div class="recipient-text text-truncate-75">
					<%= c.engaged_participations.distinct.map { |ep| ep.user.first_name }.join(', ') %>
					<%= "(" + c.comments.count.to_s + ")" if c.comments.count > 1 %>
				</div>

				<div class="preview-text text-truncate"><%= strip_tags(c.comments.last.content.gsub('<br>',' ').gsub('&nbsp;',' ')) %></div>
			</div>
		</a>
	<% end %>
</div>

<!-- <div class="bottom-bar">
	
</div> -->

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div class="section">
		<%= render 'conversation_list' %>
	</div>
<% else %>

	<div class="section">
		<div class="page-content center">
			<h1>
				Deep conversations with the right people 
				<span style="display: inline-block;">are priceless.</span>
			</h1>

			<div id="carousel-home" class="carousel slide carousel-fade" data-ride="carousel">
				<div class="carousel-inner" role="listbox">
					<!-- image credit: illustrators at 16 personalities -->
					<div class="item active"><img src="/images/h_friendship.png" alt="friendship"></div>
					<div class="item"><img src="/images/h_relationship.png" alt="relationship"></div>
					<div class="item"><img src="/images/h_reflection.png" alt="reflection"></div>
				</div>
			</div>
			<%= link_to "GET STARTED", new_user_registration_path, class: "btn btn-primary btn-primary-action" %>
			<%= link_to "LOGIN", new_user_session_path, class: "btn btn-default btn-default-action" %>
		</div>

		<div class="page-content fit-top-border">
			<h5>About</h5>
	
			<p>
				A couple of my really close friends and I enjoy having deep conversations about random topics. Topics we find interesting. Topics we'd like to get each others views on. 
			</p>
			<p>
				While we were in college, this happened in person. Since then, life has happened to us. We live in different cities now. We keep up with each other but our discussions are lost. We found ourselves sharing links in our whatsapp group or sending email and essentially asking 'what are you thoughts?'.
			</p>
			<p>
				That is why I've built this. This is where we have conversations at our own time, without them getting buried under tons of work email or day-to-day chatter. 
			</p>
			<p>
				And I hope the same for you. That you have fun discussing, debating, and reflecting on ideas you care about with close friends.
			</p>
			<p>
				My name is Pranav Gupta and I'm a PhD student at CMU. My research involves studying how people make decisions when working in teams and what makes some teams smarter than others.
			</p>
		</div>

		<div class="page-content fit-top-border">
			<h5>This is not a startup.</h5>

			<p>
				A bunch of people have asked me: what is the value proposition of this product? What is the problem that you are solving? Why should I be using this? How rapidly are you growing? Well, the answer is simple. This is not solving any of your burning problems. There is no value addition. I'm not selling anything. I'm not even trying to grow. This is not a startup.
			</p>
			<p>
				Discussions with friends are a lot of fun. I'm doing this because I enjoy doing this. And that is all there is to it. If you find someone who attempts to say that you should have fun because it is good for you - Run! Run as far away as you can from that person!
			</p>
			<p>
				If you aren't my friend, I'll probably not bother you beyond a welcome email. I enjoy my private conversations. You can do the same if you so choose to. 
			</p>
		</div>
	</div>

<% end %>


<script type="text/javascript">
	$('.carousel').carousel();
</script>

app/views/pages/notification_settings.html.erb
<div class="section">
  <div class="top-bar">
    <div class="main-nav-text">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Email Notifications <i class="fa fa-caret-down fa-fw"></i> 
      </a>
      <ul class="dropdown-menu left-dropdown">
        <li><%= link_to "Basic Information", edit_user_registration_path %></li>
        <li><%= link_to "Email Notifications", notification_settings_path, class: "active-link" %></li>
      </ul>
    </div>
  </div>

  <div class="fit-list">

		<!-- FRIENDSHIP NOTIFICATIONS -->
  	<div class="fit-list-actions">
			<% if current_user.friendship_notifications? %>
				<%= link_to '<i class="fa fa-fw fa-square"></i>'.html_safe, toggle_friendship_notification_path, method: :post, class: "action-unread" %>
			<% else %>
				<%= link_to '<i class="fa fa-fw fa-square-o"></i>'.html_safe, toggle_friendship_notification_path, method: :post, class: "action-read" %>
			<% end %>
		</div>
  	<div class="fit-list-item">
			<h5>Friendship Changes</h5>
			<div class="recipient-text">
				Recieve email for every new friend request and accepted friend request.
			</div>
	    <div class="preview-text">
				Status: <%= current_user.friendship_notifications? ? 'ON' : 'OFF' %>
			</div>
		</div>

		<!-- CONVERSATION NOTIFICATIONS -->
		<div class="fit-list-actions">
			<% if current_user.conversation_notifications? %>
				<%= link_to '<i class="fa fa-fw fa-square"></i>'.html_safe, toggle_conversation_notification_path, method: :post, class: "action-unread" %>
			<% else %>
				<%= link_to '<i class="fa fa-fw fa-square-o"></i>'.html_safe, toggle_conversation_notification_path, method: :post, class: "action-read" %>
			<% end %>
		</div>
  	<div class="fit-list-item">
			<h5>New Discussions</h5>
			<div class="recipient-text">
				Recieve email for every new discussion your friends start with you.
			</div>
	    <div class="preview-text">
				Status: <%= current_user.conversation_notifications? ? 'ON' : 'OFF' %>
			</div>
		</div>

		<!-- REPLY NOTIFICATIONS -->
		<div class="fit-list-actions">
			<% if current_user.reply_notifications? %>
				<%= link_to '<i class="fa fa-fw fa-square"></i>'.html_safe, toggle_reply_notification_path, method: :post, class: "action-unread" %>
			<% else %>
				<%= link_to '<i class="fa fa-fw fa-square-o"></i>'.html_safe, toggle_reply_notification_path, method: :post, class: "action-read" %>
			<% end %>
		</div>
  	<div class="fit-list-item">
			<h5>New Replies</h5>
			<div class="recipient-text">
				Recieve email for every new reply by a friend in any discussion. Alternatively, you can mute specific discussions.
			</div>
	    <div class="preview-text">
				Status: <%= current_user.reply_notifications? ? 'ON' : 'OFF' %>
			</div>
		</div>

	</div>
</div>